### ISSUE TITLE
Destroying with where clause

### ISSUE THREAD

**Issue by slavik57** [seegno/bookshelf-cascade-delete#14]
The next code throws error:

`new User().where({ username: 'some username' }).destroy();`

This happens because of the code in the 'recursiveDeletes' function:

`var parentValue = typeof parent === 'number' || typeof parent === 'string' ? '\'' + parent + '\'' : parent.toString();`

Because there is no id so the `parent` is undefined...

**Comment by ricardogama** [comment]
@slavik57 Thanks for the report, a fix for this issue has been released in [1.0.4](https://github.com/seegno/bookshelf-cascade-delete/releases). Cheers!
