### ISSUE TITLE
Self relations

### ISSUE THREAD

**Issue by saltas888** [seegno/bookshelf-cascade-delete#30]
hello, what if we have a self relation? I'm getting Maximum call stack size exceeded in the following model:

``` javascript
const Organisation = bookshelf.Model.extend({
  tableName: 'organisations',

  hasTimestamps: true,

  users: function() {
    return this.hasMany(User, 'OrganisationId');
  },
  clientOfOrganisation: function(){
    return this.belongsTo(Organisation, 'clientOfOrganisationId')
  },
  organisations: function(){
    return this.hasMany(Organisation, 'clientOfOrganisationId'); 
  },
},{
  dependents: ['users', 'organisations'],

  byName: function(name, params = {}){
    return this.forge().query({where:{ name: name }}).fetch(params);
  }
})
```

I think that the error exists in the following block, where the dependency map is building:

``` javascript

    dependencyMap(skipDependents = false) {
      if (skipDependents || !this.dependents) {
        return;
      }

      return reduce(this.dependents, (result, dependent) => {
        const { relatedData } = this.prototype[dependent]();
        const skipDependents = relatedData.type === 'belongsToMany';

        return [
          ...result, {
          dependents: relatedData.target.dependencyMap(skipDependents),
          key: relatedData.key('foreignKey'),
          model: relatedData.target,
          skipDependents,
          tableName: skipDependents ? relatedData.joinTable() : relatedData.target.prototype.tableName
        }];
      }, []);
    },
```

P.S. Is there an ES6 class support?

**Comment by ricardogama** [comment]
Hi @saltas888.

This plugin does not support self relations because the dependency map is recursively built, the same happens if you create circular dependents.

I could add a condition to not propagate the cascading if the target and parent models are the same  but it wouldn't be flawless on second level dependents, for example:

| id | clientOfOrganisationId |
| --- | --- |
| 1 | NULL |
| 2 | 1 |
| 3 | 2 |

The generated queries on the destroying first row would be:

``` sql
delete from "Organisation" where "clientOfOrganisationId" IN (1)
delete from "Organisation" where "id" = 1
```

The third row would not be deleted and a potential foreign key violation thrown, so I'm sorry but I guess there's nothing we can do about self relations.

**Comment by saltas888** [comment]
Ok thank you for the informations. I just delete the self-dependency manually.

About es6 classes? Do you have an usage example with classes?

**Comment by ricardogama** [comment]
I'm not sure what do you mean, like extending Bookshelf models as classes? Can you give an example?

**Comment by saltas888** [comment]
Sure, the above as i had it before i use your module:

``` javascript
export default class Organisation extends db.Model {  
  get tableName() {
    return 'organisations';
  }

  get hasTimestamps() {
    return true;
  }
  users() {
    return this.hasMany(User, 'OrganisationId');
  }
  clientOfOrganisation(){
    return this.belongsTo(Organisation, 'clientOfOrganisationId')
  }
  static byName(name, params = {}){
    return this.forge().query({where:{ name: name }}).fetch(params);
  }
}
```

**Comment by ricardogama** [comment]
Honestly I never used classes on Bookshelf models, always used the `extend` method. So you're saying the plugin does not work when you're extending `Bookshelf.model`, right? I'll look into it.

**Comment by ricardogama** [comment]
@saltas888 Have you tried to define `dependents` as static? 

``` js
export default class Organisation extends db.Model {  
  static dependents = ['users', 'organisations'];

  get tableName() {
    return 'organisations';
  }

  ...
}
```

**Comment by saltas888** [comment]
No :). Thank you. I ll try it!
I was using it without the static :/

**Comment by ricardogama** [comment]
Let me know if it works and I'll add that to the documentation.

**Comment by ricardogama** [comment]
@saltas888 Can I close this?

**Comment by saltas888** [comment]
Hello , sorry for the delay.
So yes it works! you could add it.
Thank you again

**Comment by ricardogama** [comment]
You're welcome, cheers!
