### ISSUE TITLE
Can you release current master to npm?

### ISSUE THREAD

**Issue by annahassel** [seegno/bookshelf-cascade-delete#34]
There aren't any releases from august, but there are a few helpful commits, e.g. [better postgres config support](https://github.com/seegno/bookshelf-cascade-delete/commit/3131e997970f2996cf427c49de3232e66eea977f). Thank you.

**Comment by ricardogama** [comment]
Released as [2.0.1](https://github.com/seegno/bookshelf-cascade-delete/releases/tag/2.0.1).
